### **UNIVERSIDADE FEDERAL DE ITAJUBÁ**
### **Instituto de Matemática e Computação**
### **Ciência da Computação**

--

### **CMAC03 - Algoritmos em Grafos**

### **Tópico: 1. Introdução à Grafos**

## **Aula Prática - Python Básico**

---

**Objetivo:** Este notebook tem por objetivo apresentar a linguagem que será adotada para implementação dos algoritmos que serão abordados na disciplina. Ele pode ser usado como ambiente de desenvolvimento alternativo à IDE e ao Moodle. Contudo, visando uma maior autonomia do aluno, a recomendação é que seja utilizada uma IDE instalada localmente no seu equipamento.

Para cada enunciado a seguir implemente os códigos de modo a atender o que se pede.

---

## **Matrícula:** 2022000468
## **Nome:** João Vitor Ribeiro de Bona
---


## **0. Bibliotecas**

É recomendável adicionar as bibliotecas necessárias logo no início do código seguindo uma boa prática de programação além de evitar futuros problemas. **Obs**: Use a célula abaixo para as bibliotecas que forem necessárias.

**Q1.** Instale a biblioteca iGraph (https://python.igraph.org/en/stable/).

In [ ]:
!pip install python-igraph

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 28.8 MB/s eta 0:00:00


**Q2.** Importe as seguintes bibliotecas: numpy, time, math, random, igraph. Faça a montagem de uma pasta no repositório do Google Drive que contenha os *datasets* sobre grafos disponíveis no SIGAA (simples, ponte, zachary).

In [ ]:
import igraph as ig
import numpy as np
import time
import math

---
## **1. Variáveis e *Strings***

**Q3.** Crie uma variável do tipo *string* que recebe um valor de entrada dado pelo usuário e retorna um valor do tipo inteiro que é o triplo do valor fornecido.

In [ ]:
i = input("Digite um número: ")
n = int(i)
triplo = n * 3
print("O triplo do número é:", triplo)

Digite um número: 3
O triplo do número é: 9



**Q4.** Concatene duas *strings* dadas pela entrada do usuário e cujos caracteres estão todos em caixa baixa (minúsculos), de modo que o primeiro caracter de cada string se torne caixa alta (maiúsculo).

In [ ]:
str1 = input("Digite a primeira frase: ")
str2 = input("Digite a segunda frase: ")

r = str1.capitalize() + str2.capitalize()

print("Resultado concatenado:", r)

Digite a primeira frase: meu nome 
Digite a segunda frase: é marcos
Resultado concatenado: Meu nome É marcos


---
## **2. Entrada e Saída**

**Q5.** Implemente uma função que recebe como entrada o nome de um *dataset* armazenado no seu Google Drive (ex. simples, ponte, zachary), lê o respectivo arquivo .txt, atribua o conteúdo do arquivo a um objeto tipo `numpy.ndarray`, imprime na tela a respectiva matriz e o seu tipo.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
caminho_arquivo = '/content/drive/My Drive/exemplo.txt'


m = np.loadtxt(caminho_arquivo)
print("Matriz:")
print(m)
print("\nTipo do objeto:", type(m))


Matriz:
[[0. 1. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1. 1. 0.]
 [0. 0. 1. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 1. 0.]]

Tipo do objeto: <class 'numpy.ndarray'>


**Q6.** Obtenha as dimensões da matriz no formato (linhas, colunas), bem como a lista com os valores constantes na sua diagonal.

In [ ]:
linhas, colunas = m.shape
print("\nDimensões da matriz: ({}, {})".format(linhas, colunas))

diagonal = np.diagonal(m)
print("\nDiagonal principal:", diagonal.tolist())


Dimensões da matriz: (7, 7)

Diagonal principal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


**Q7.** Usando a matriz obtida em Q5, imprima o elemento da posição [i][j] informado pelo usuário. Informe caso algum índice dado na entrada seja maior que a dimensão da matriz.

In [ ]:
try:
        i = int(input("\nDigite a linha i desejada: "))
        j = int(input("Digite a coluna j desejada: "))

        if i < 0 or j < 0:
            print("Índices não podem ser negativos.")
        elif i >= linhas or j >= colunas:
            print("Erro: índice fora dos limites da matriz.")
        else:
            print(f"Elemento da posição [{i}][{j}]: {m[i][j]}")

except ValueError:
        print("Entrada inválida. Por favor, digite números inteiros.")


Digite a linha i desejada: 4
Digite a coluna j desejada: 6
Elemento da posição [4][6]: 0.0


**Q8.** Salve em um arquivo no seu Google Drive com o nome "resultado.txt", lista dos valores da diagonal da matriz obtida em Q6.

In [ ]:
caminho_salvar = '/content/drive/My Drive/resultado.txt'

diagonal_str = 'Valores da diagonal principal:\n' + ', '.join(map(str, diagonal.tolist()))

with open(caminho_salvar, 'w') as f:
    f.write(diagonal_str)

print(f"\nLista salva em Arquivo!")


Lista salva em Arquivo!


---
## **3. Estruturas**

**Q9.** A partir da matriz, implemente uma função que constroi um dicionário. Cada chave do dicionário corresponde ao índice da linha da matriz. O valor de cada chave corresponde a uma lista com os índices das colunas associadas à linha em questão, que possuam valor maior que 0. Caso o valor da coluna seja maior que 1 deve-se repetir o índice da coluna conforme o valor (ex. a célula dada pela linha 1 e coluna 2 tem valor 4, logo, o valor 2 na lista da linha 1 precisará ser repetido 4 vezes).

In [ ]:
def construir_dicionario(m):
    dicionario = {}
    linhas, colunas = m.shape

    for i in range(linhas):
        colunas_positivas = []
        for j in range(colunas):
            valor = int(m[i][j])
            if valor > 0:
                colunas_positivas.extend([j] * valor)
        dicionario[i] = colunas_positivas

    return dicionario

dicionario_resultado = construir_dicionario(m)

print("\nDicionário da matriz:")
for chave, valor in dicionario_resultado.items():
    print(f"{chave}: {valor}")


Dicionário da matriz:
0: [1, 2, 5]
1: [0]
2: [0, 3, 4, 5]
3: [2, 4, 6]
4: [2, 3]
5: [0, 2, 6]
6: [3, 5]


**Q10.** Calcule o tempo total de execução da função que implementou em Q9, considerando precisão de 4 (quatro) casas decimais.

In [ ]:
inicio = time.time()
dicionario_resultado = construir_dicionario(m)
fim = time.time()

tempo_execucao = fim - inicio

print(f"{tempo_execucao:.4f}")

0.0002



**Q11.** Crie uma lista que armazene os valores de uma linha da matriz obtida em Q5, cujo índice da linha é dado como entrada. Imprima na tela essa lista e a sua versão invertida.

In [ ]:
try:
    i = int(input("Digite a linha i desejada: "))

    if i < 0 or i >= m.shape[0]:
        print("Erro: índice fora da matriz.")
    else:
        linha = m[i].astype(int).tolist()
        linha_invertida = linha[::-1]

        print(linha)
        print(linha_invertida)

except ValueError:
    print("Entrada inválida. Por favor, digite um número inteiro.")

Digite a linha i desejada: 4
[0, 0, 1, 1, 0, 0, 0]
[0, 0, 0, 1, 1, 0, 0]


**Q12.** Considere a lista obtida em Q11 e altere o elemento que consta na posição 1 dessa lista para o valor 2.

In [ ]:
try:
    i = int(input("Digite a linha i desejada: "))

    if i < 0 or i >= m.shape[0]:
        print("Erro: índice fora dos limites da matriz.")
    else:
        linha_lista = m[i].astype(int).tolist()

        linha_lista[1] = 2
        print(linha_lista)

except ValueError:
    print("Entrada inválida. Por favor, digite um número inteiro.")

Digite a linha i desejada: 4
[0, 2, 1, 1, 0, 0, 0]


**Q13.** Considerando a lista obtida em Q11, inclua o elemento 5 no final dessa lista e inclua o elemento 3 na posição 1 da lista.

In [ ]:
try:
    i = int(input("Digite a linha i desejada: "))

    if i < 0 or i >= m.shape[0]:
        print("Erro: índice fora dos limites da matriz.")
    else:
        linha_lista = m[i].astype(int).tolist()

        linha_lista[1] = 2

        linha_lista.append(5)

        linha_lista.insert(1, 3)
        print(linha_lista)

except ValueError:
    print("Entrada inválida. Por favor, digite um número inteiro.")

Digite a linha i desejada: 4
[0, 3, 2, 1, 1, 0, 0, 0, 5]


---
## **4. Estruturas de Repetição**

**Q14.** Crie uma função que recebe um número do usuário e imprime na tela uma contagem regressiva até o valor 1. Utilize o comando `for`.

In [ ]:
def contagem_regressiva():
    try:
        n = int(input("Digite um número: "))

        if n < 1:
            print("Digite um número maior ou igual a 1.")
        else:
            for i in range(n, 0, -1):
                print(i)

    except ValueError:
        print("Entrada inválida. Por favor, digite um número inteiro.")

contagem_regressiva()
print("Terminou")

Digite um número: 10
10
9
8
7
6
5
4
3
2
1
Terminou


**Q15.** Implemente a mesma função solicitada em Q14, mas utilizando o comando `while`.

In [ ]:
def contagem_regressiva_while():
    try:
        n = int(input("Digite um número: "))

        if n < 1:
            print("Por favor, digite um número maior ou igual a 1.")
        else:
            while n >= 1:
                print(n)
                n -= 1

    except ValueError:
        print("Entrada inválida. Por favor, digite um número inteiro.")

contagem_regressiva_while()
print("Terminou")

Digite um número: 10
10
9
8
7
6
5
4
3
2
1
Terminou


**Q16.** Implemente a mesma função solicitada em Q14, utilizando uma função recursiva.

In [ ]:
def contagem_regressiva_recursiva(n):
    if n < 1:
        return
    print(n)
    contagem_regressiva_recursiva(n - 1)

def iniciar_contagem_recursiva():
    try:
        n = int(input("Digite um número: "))
        if n < 1:
            print("Por favor, digite um número maior ou igual a 1.")
        else:
            contagem_regressiva_recursiva(n)


    except ValueError:
        print("Entrada inválida. Por favor, digite um número inteiro.")

iniciar_contagem_recursiva()
print("Terminou")

Digite um número: 10
10
9
8
7
6
5
4
3
2
1
Terminou


---
## **5. Resolução de Problemas**

**Q17.** Calcule a área de uma circunferência com base no raio recebido pelo usuário. Imprima na tela o resultado.

In [ ]:
def area():
    try:
        raio = float(input("Digite o raio da circunferência: "))
        if raio < 0:
            print("O raio não pode ser negativo.")
        else:
            area = math.pi * raio ** 2
            print(f"\nA área da circunferência é: {area:.2f}")
    except ValueError:
        print("Entrada inválida. Por favor, digite um número.")

area()

Digite o raio da circunferência: 5

A área da circunferência é: 78.54



**Q18.** Crie um programa que recebe duas notas do usuário e retorna uma mensagem com base na aprovação ou reprovação considerando média maior ou igual a 6,0.

In [ ]:
def media_total():
    try:
        nota1 = float(input("Digite o valor da nota 1: "))
        nota2 = float(input("Digite o valor da nota 2: "))

        media = (nota1 + nota2) / 2

        if media >= 6.0:
            print(f"Parabéns sua média foi {media:.2f} e você foi APROVADO!!")
        else:
            print(f"Infelizmente sua média foi {media:.2f} e você foi REPROVADO!!")

    except ValueError:
        print("Entrada inválida. Por favor, digite números válidos para as notas.")

media_total()

Digite o valor da nota 1: 4.7
Digite o valor da nota 2: 5.9
Infelizmente sua média foi 5.30 e você foi REPROVADO!!


**Q19.** Implemente uma função que recebe uma medida de ângulo em graus e retorna uma mensagem indicando o seu quadrante.

In [ ]:
def quadrante():
    try:
        angulo = float(input("Digite o valor do ângulo em graus(0 a 360): "))

        angulo = angulo % 360

        if 0 <= angulo <= 90:
            print("1º quadrante")
        elif 90 < angulo <= 180:
            print("2º quadrante")
        elif 180 < angulo <= 270:
            print("3º quadrante")
        elif 270 < angulo <= 360:
            print("4º quadrante")
    except ValueError:
        print("Entrada inválida. Por favor, digite um número.")

quadrante()

Digite o valor do ângulo em graus(0 a 360): 180
2º quadrante
